name: mausoleum

description: Flutter new project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  
  path: ^1.8.3
  path_provider: ^2.0.15
  synchronized: ^3.1.0  
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  sqlite_bm25: ^0.3.0
  styled_text: ^8.1.0
  extractor: ^0.0.3
  flutter_screenutil: ^5.8.4
  in_app_update: ^4.1.4
  dio: ^5.3.3
  fluttericon: ^2.0.0
  permission_handler: ^11.0.1
  water_drop_nav_bar: ^2.2.0+5
  file_manager: ^1.0.2
  flutter_video_info: ^1.3.1
  file_picker: ^6.1.1 
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.6
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0
  rive: ^0.11.14
  gif_view: ^0.4.0 
  qr_flutter: ^4.1.0
  qr_scanner: ^0.0.2-259.9.beta
  mobile_scanner: ^3.4.1
  yandex_mapkit: ^3.3.3
  easy_localization: ^3.0.3
  dropdown_button2: ^2.3.9
  provider: ^6.0.5
  riverpod: ^2.4.0
  audioplayers: ^5.1.0  
  on_audio_query: ^2.9.0
  just_audio: ^0.9.35
  flutter_sound: ^9.2.13
  saver_gallery: ^2.0.1
  downloads_path_provider_28: ^0.1.2
  excel: ^4.0.0
  audio_session: ^0.1.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/translations/

flutter_icons:
  android: launcher_icon
  image_path: assets/images/launcher_icon.png
  ios: true
  remove_alpha_ios: true